config/routes.rb
Rails.application.routes.draw do
  root to: "games#show"

  resource :game, only: %i(show update)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def show
    @game = HangmanGame.new.start_the_game("user@example.com")

    session[:game] = { key: @game["game_key"], tries_left: @game["num_tries_left"] }

    render :show
  end

  def update
    tries_left = session[:game]["tries_left"].to_i
    guess = HangmanGame.new.guess(session[:game]["key"], game_params[:guess])
    puts "json is ", guess.except("game_key").merge(wrong: tries_left > guess["num_tries_left"].to_i)
    render json: guess.except("game_key").merge(wrong: tries_left > guess["num_tries_left"].to_i)
  end

  private

  def game_params
    params.require(:game).permit(:guess)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/show.html.slim
.hangman
  .hangman__canvas
    .gallows
      .gallows__part.gallows__part--1
      .gallows__part.gallows__part--2
      .gallows__part.gallows__part--3
      .gallows__part.gallows__part--4
      .gallows__part.gallows__part--5
    .man
      i.man__head
      i.man__body
      i.man__leg.man__leg--left
      i.man__leg.man__leg--right
      i.man__arm.man__arm--right
      i.man__arm.man__arm--left

  .hangman__letters
    h3
      - ("A".."Z").each do |char|
        => link_to char, game_path, remote: true, method: :patch, class: "guess", data: { params: { game: { guess: char } } }

  .hangman__phrase
    h3#phrase= @game["phrase"]

  .hangman__new-game
    = link_to 'Start new game', 'javascript:location.reload();'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hangman</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', 'https://fonts.googleapis.com/css?family=Fontdiner+Swanky', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>